name: Build and Publish

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm test
      - run: |
          DATE_PART=$(date "+%Y-%m-%d")
          COMMIT_PART=$(git rev-parse --short HEAD)
          echo "VERSION_COMMIT=${DATE_PART}_${COMMIT_PART}" >> $GITHUB_ENV
      - run: npm run mwi
      - run: npm run grid-trading
      - uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          name: github-pages
          path: dist
      - id: deployment
        uses: actions/deploy-pages@v4
